name: advanced_mobile_app_development
description: "The Flutter app for the module AMAD at HSMW."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  http: ^1.2.2
  sensors_plus: ^6.1.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  flutter_vision:
    git:
      url: https://github.com/zeexan-dev/flutter_vision.git
  image: ^4.5.4
  camera: ^0.11.2
  flutter_local_notifications: ^19.4.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700